{% set name = "legendary-gl" %}
{% set version = "0.20.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/legendary-gl-{{ version }}.tar.gz
  sha256: de84a2f8b3fb85d45128ac5386cf8e9280764785faa87341cb07181fab20bddd

build:
  number: 0
  noarch: python
  entry_points:
    - legendary = legendary.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - requests <3.0
    - setuptools
    - wheel

test:
  imports:
    - legendary
    - legendary.api
  commands:
    - pip check
    - legendary --help
  requires:
    - pip

about:
  home: https://github.com/derrod/legendary
  summary: Free and open-source replacement for the Epic Games Launcher application
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
