{% set name = "legendary-gl" %}
{% set version = "0.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 88f90cdcb146d1a9253e6885a590d1ca0420d52d40460f1164f7b0c6991b7522

build:
  number: 0
  noarch: python
  entry_points:
    - legendary = legendary.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - uv-build >=0.11.4,<0.12
  run:
    - python >={{ python_min }}
    - filelock
    - requests
    - pycryptodomex

test:
  imports:
    - legendary
    - legendary.api
  commands:
    - pip check
    - legendary --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/derrod/legendary
  summary: Free and open-source replacement for the Epic Games Launcher application
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
